name: Build Windows

on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.20.13'
      
    - name: Build windows amd64 binary
      run: |
        env CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w" -o rmmagent-amd64-windows.exe
    - name: Build windows 386 binary
      run: |
        env CGO_ENABLED=0 GOOS=windows GOARCH=386 go build -ldflags "-s -w" -o rmmagent-386-windows.exe

    - name: Upload amd64 Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: rmmagent-amd64-windows
        path: rmmagent-amd64-windows.exe

    - name: Upload 386 Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: rmmagent-386-windows
        path: rmmagent-386-windows.exe

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rmmagent-amd64-windows.exe
          rmmagent-386-windows.exe
        tag_name: testing
        name: "Windows Release for Testing"
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
