# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go
# Based from: https://github.com/kylefmohr/MacOSRMM-Script/blob/main/.github/workflows/go.yml
name: Build MacOS

on:
  #push:
  #  branches: [ "main" ]
  #pull_request:
  #  branches: [ "main" ]
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag to release under'
        required: false
        default: 'Unknown'
        
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone GuillaumeFalourd/poc-github-actions PUBLIC repository
      uses: GuillaumeFalourd/clone-github-repo-action@v2.3
      with:
        depth: 1
        branch: 'master'
        owner: 'amidaware'
        repository: 'rmmagent'

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
      
    - name: Build amd64 binary
      run: cd rmmagent && env CGO_ENABLED=0 GOOS=darwin GOARCH=amd64 go build -ldflags "-s -w" && mv rmmagent rmmagent-amd64-macos

    - name: Build arm64 binary
      run: cd rmmagent && env CGO_ENABLED=0 GOOS=darwin GOARCH=arm64 go build -ldflags "-s -w" && mv rmmagent rmmagent-arm64-macos

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: rmmagent-amd64-macos
        path: rmmagent/rmmagent-amd64-macos
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.0
      with:
        name: rmmagent-arm64-macos
        path: rmmagent/rmmagent-arm64-macos

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          rmmagent/rmmagent-amd64-macos
          rmmagent/rmmagent-arm64-macos
        tag_name: ${{ github.event.inputs.tag_name }}
        name: ${{ github.event.inputs.tag_name }}
        draft: false
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
